#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

providers:
  mockbank:
    url: https://hydra.softmagic.local/
    clientID: hub-auth
    clientSecret: hub-auth-secret
