--- #---------------- Chaincode Service ---------------------
apiVersion: v1
kind: Service
metadata:
  name: chaincode-marbles-myorg1
  namespace: hlf
  labels:
    app: chaincode-marbles-myorg1
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-marbles-myorg1
