--- #---------------- CA org1 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ca1-myorg1
  name: ca1-myorg1
  namespace: hlf
spec:
  selector:
    matchLabels:
      app: ca1-myorg1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ca1-myorg1
    spec:
      containers:
        - args:
            - sh
            - -c
            - fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.myorg1-cert.pem
              --ca.keyfile /etc/hyperledger/fabric-ca-server-config/{ORG1-CA-KEY}
              -b admin:adminpw -d
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca1-myorg1
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.myorg1-cert.pem
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/{ORG1-CA-KEY}
          image: hyperledger/fabric-ca:1.4.7
          name: ca1-myorg1
          ports:
            - containerPort: 7054
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: ca1-myorg1-drv0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: ca1-myorg1-drv0
          hostPath:
            path: {HOME_DIR_PATH}/crypto-config/peerOrganizations/myorg1/ca/
            type: Directory
