#---------------- CA OE1 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ca1-myorg1
  name: ca1-myorg1
  namespace: hlf
spec:
  type: ClusterIP
  ports:
  - name: "https"
    port: 7054
    targetPort: 7054
  selector:
    app: ca1-myorg1
