version: '3.3'
services:
  client-web:
    image: softmagic/client-web:latest
    # volumes:
    #   - mongodb_container:/data/db
    volumes:
      - ./nginx//keys/tls:/etc/nginx/certs
      # - ./nginx/client/log:/var/log/nginx:ro 
    environment:
      - VIRTUAL_HOST=client.softmagic.local
      # - VIRTUAL_PORT=8085
      - TLS_CERT=/etc/nginx/certs/softmagic.local.crt
      - TLS_KEY=/etc/nginx/certs/softmagic.local.key
    ports:
      - 8085:80
    depends_on:
      - mongo
      - postgresql
    networks:
      - product-net
  
  server:
    image: softmagic/api-server:latest
    # volumes:
    #   - ./server:/server
    environment:
      - VIRTUAL_HOST=server.softmagic.local
      # - VIRTUAL_PORT=3030
    restart: always
    ports:
      - 3030:3030
    volumes:
      - ./nginx//keys/tls:/usr/server/config/cert
    depends_on:
      - mongo
      - postgresql
    networks:
      - product-net
    
  postgresql:
    image: frodenas/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DBNAME=mydb
      - POSTGRES_EXTENSIONS=citext
    volumes:
      - postgresql_container:/var/lib/postgresql/data
    networks:
        - product-net

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db
    networks:
      - product-net

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx//keys/tls:/etc/nginx/certs
      - ./nginx/log:/var/log/nginx 
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/config:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=softmagic.local
    networks:
      # - product-net
      product-net:
        aliases:
          - client.softmagic.local
          - server.softmagic.local
 
volumes:
  mongodb_container:
  postgresql_container:

networks:
  product-net:
    driver: bridge
    # external: true

  