version: '3.3'
services:
  client-web:
    image: softmagic/client-web:latest
    # volumes:
    #   - mongodb_container:/data/db
    ports:
      - 8085:8080
    depends_on:
      - mongo
      - postgresql
    networks:
      - product-net

  server:
    image: softmagic/api-server:latest
    # volumes:
    #   - ./server:/server
    ports:
      - 3030:3030
    depends_on:
      - mongo
      - postgresql
    networks:
      - product-net
    
  postgresql:
    image: frodenas/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DBNAME=mydb
      - POSTGRES_EXTENSIONS=citext
    volumes:
      - postgresql_container:/var/lib/postgresql/data
    networks:
        - product-net

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db
    networks:
      - product-net

volumes:
  mongodb_container:
  postgresql_container:

networks:
  product-net:
