version: '3.3'
services:
  app:
    image: node:lts-alpine
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - 8085:8085
    networks:
      - demo-net
    command: >
      sh -c "npm install -g @quasar/cli && npm install &&
             quasar dev"
    

  server:
    image: node:lts-alpine
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - 3030:3030
    depends_on:
      - mongo
      - postgresql
    # NODE_ENV variable is used by feathersjs to determine which config
    # file to merge with the default.json file. Update as needed.
    environment:
      NODE_ENV: dev
    command: >
      sh -c "npm install && npm run dev-test"
    networks:
      - demo-net
  
  # vault:
  #   image: vault:latest
  #   container_name: vault
  #   restart: on-failure:10
  #   ports:
  #     - "8201:8201"
  #   environment:
  #     VAULT_ADDR: 'https://0.0.0.0:8201'
  #   cap_add:
  #     - IPC_LOCK
  #   volumes:
  #     - vault-volume:/data
  #   healthcheck:
  #     retries: 5
  #   command: ./vault/workflow-vault.sh
  #   depends_on:
  #     - postgresql
  #   networks:
  #     - demo-net
    
  postgresql:
    image: frodenas/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DBNAME=mydb
      - POSTGRES_EXTENSIONS=citext
    volumes:
      - postgresql_container:/var/lib/postgresql/data
    networks:
        - demo-net

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db
    networks:
      - demo-net

volumes:
  mongodb_container:
  postgresql_container:

networks:
  demo-net:
# 
# version: "2"

# services:
#   api:
#     container_name: "be"
#     image: <image_name>:latest
#     ports:
#       - "8000:8000"
#     environment:
#       DB_HOST: host.docker.internal
#       DB_USER: <your_user>
#       DB_PASS: <your_pass>
#     networks: 
#       - mynw

#   db:
#     container_name: "psql"
#     image: postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: <your_postgres_db_name>
#       POSTGRES_USER: <your_postgres_user>
#       POSTGRES_PASS: <your_postgres_pass>
#     volumes:
#       - ~/dbdata:/var/lib/postgresql/data
#     networks:
#       - mynw