--- #---------------- Orderer0 Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {ORD_NAME0}
  name: {ORD_NAME0}
  namespace: {K8S_NS}
spec:
  selector:
    matchLabels:
      app: {ORD_NAME0}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {ORD_NAME0}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - {ORD_NAME1}
                        - {ORD_NAME2}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - args:
            - orderer
          env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: ORDERER_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:8443
            - name: ORDERER_METRICS_PROVIDER
              value: prometheus
            - name: ORDERER_GENERAL_GENESISFILE
              value: /var/hyperledger/orderer/genesis.block
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /var/hyperledger/orderer/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: {ORD_NAME0_C}MSP
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
          image: hyperledger/fabric-orderer:{IMAGE_TAG}
          name: orderer
          ports:
            - containerPort: 7050
            - containerPort: 8443
          volumeMounts:
            - mountPath: /var/hyperledger/production
              name: orderer-persistentdata
            - mountPath: /var/hyperledger/orderer/genesis.block
              name: orderer-drv0
            - mountPath: /var/hyperledger/orderer/msp
              name: orderer-drv1
            - mountPath: /var/hyperledger/orderer/tls
              name: orderer-drv2
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric
      restartPolicy: Always
      volumes:
        - name: orderer-persistentdata
          hostPath:
            path: /home/ravi/storage/orderer0
            type: DirectoryOrCreate
        - name: orderer-drv0
          hostPath:
            path: {HOME_DIR_PATH}/channel-artifacts/genesis.block
        - name: orderer-drv1
          hostPath:
            path: {HOME_DIR_PATH}/crypto-config/ordererOrganizations/{DOMAIN_NAME}/orderers/{ORD_NAME0}/msp
        - name: orderer-drv2
          hostPath:
            path: {HOME_DIR_PATH}/crypto-config/ordererOrganizations/{DOMAIN_NAME}/orderers/{ORD_NAME0}/tls
  