--- #---------------- Orderer0 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {ORD_NAME0}
  name: {ORD_NAME0}
  namespace: {K8S_NS}
spec:
  type: ClusterIP
  ports:
    - name: "orderer"
      port: 7050
      targetPort: 7050
  selector:
    app: {ORD_NAME0}
---
#---------------- Orderer0 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {ORD_NAME0}
    metrics-service: "true"
  name: {ORD_NAME0}-metrics
  namespace: {K8S_NS}
spec:
  type: ClusterIP
  ports:
    - name: "orderer-metrics"
      port: 8443
      targetPort: 8443
  selector:
    app: {ORD_NAME0}
