version: '3.2'

networks:
  dswarm_net:
    external: 
      name: dswarm_net

services:

  peer0_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
      placement:
        constraints:
          - node.hostname == 
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: peer0.org2.dstest.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=dswarm_net
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dswarm_net
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.dstest.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_ID=peer0.org2.dstest.com
      - CORE_PEER_ADDRESS=peer0.org2.dstest.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.dstest.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.dstest.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_org2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    volumes:
      - /var/run/:/host/var/run/
      - ../../crypto-config/peerOrganizations/org2.dstest.com/peers/peer0.org2.dstest.com/msp:/etc/hyperledger/msp
      - ../../crypto-config/peerOrganizations/org2.dstest.com/peers/peer0.org2.dstest.com/tls:/etc/hyperledger/tls
      - ../../crypto-config/peerOrganizations/org2.dstest.com/users:/etc/hyperledger/users
      - ../../channel-artifacts/:/var/hyperledger/config
      #- peer0.org2.dstest.com:/etc/hyperledger/production
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    networks:
      dswarm_net:
        aliases:
          - peer0.org2.dstest.com
    ports:
      - 9051:9051
      - 9053:9053
      
  peer1_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
      placement:
        constraints:
          - node.hostname == 
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: peer1.org2.dstest.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=dswarm_net
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=dswarm_net
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.dstest.com:10052
      - CORE_PEER_ID=peer1.org2.dstest.com
      - CORE_PEER_ADDRESS=peer1.org2.dstest.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.dstest.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org2:5984
      ##
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.dstest.com:9051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    volumes:
      - /var/run/:/host/var/run/
      - ../../crypto-config/peerOrganizations/org2.dstest.com/peers/peer1.org2.dstest.com/msp:/etc/hyperledger/msp
      - ../../crypto-config/peerOrganizations/org2.dstest.com/peers/peer1.org2.dstest.com/tls:/etc/hyperledger/tls
      - ../../crypto-config/peerOrganizations/org2.dstest.com/users:/etc/hyperledger/users
      - ../../channel-artifacts/:/var/hyperledger/config
      #- peer1.org2.dstest.com:/etc/hyperledger/production
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    ports:
      - 10051:10051
      - 10053:10053
    networks:
      dswarm_net:
        aliases:
          - peer1.org2.dstest.com