version: '3.2'

networks:
  {SWARM_NET}:
    external: 
      name: {SWARM_NET}

services:

  peer0_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
      placement:
        constraints:
          - node.hostname == {ORG2_HOSTNAME}
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: {PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID={SWARM_NET}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={SWARM_NET}
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODEADDRESS={PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_ID={PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}
      - CORE_PEER_ADDRESS={PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT={PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP={PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}:10051
      - CORE_PEER_LOCALMSPID={ORG_2_C}MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_org2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    volumes:
      - /var/run/:/host/var/run/
      - ../../crypto-config/peerOrganizations/{ORG_2}.{DOMAIN_NAME}/peers/{PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}/msp:/etc/hyperledger/msp
      - ../../crypto-config/peerOrganizations/{ORG_2}.{DOMAIN_NAME}/peers/{PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}/tls:/etc/hyperledger/tls
      - ../../crypto-config/peerOrganizations/{ORG_2}.{DOMAIN_NAME}/users:/etc/hyperledger/users
      - ../../channel-artifacts/:/var/hyperledger/config
      #- {PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}:/etc/hyperledger/production
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    networks:
      {SWARM_NET}:
        aliases:
          - {PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}
    ports:
      - 9051:9051
      - 9053:9053
      
  peer1_org2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
      placement:
        constraints:
          - node.hostname == {ORG2_HOSTNAME}
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: {PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID={SWARM_NET}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE={SWARM_NET}
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # TLS settings
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODELISTENADDRESS={PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}:10052
      - CORE_PEER_ID={PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}
      - CORE_PEER_ADDRESS={PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT={PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}:10051
      - CORE_PEER_LOCALMSPID={ORG_2_C}MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org2:5984
      ##
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP={PEER_NAME0}.{ORG_2}.{DOMAIN_NAME}:9051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    volumes:
      - /var/run/:/host/var/run/
      - ../../crypto-config/peerOrganizations/{ORG_2}.{DOMAIN_NAME}/peers/{PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}/msp:/etc/hyperledger/msp
      - ../../crypto-config/peerOrganizations/{ORG_2}.{DOMAIN_NAME}/peers/{PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}/tls:/etc/hyperledger/tls
      - ../../crypto-config/peerOrganizations/{ORG_2}.{DOMAIN_NAME}/users:/etc/hyperledger/users
      - ../../channel-artifacts/:/var/hyperledger/config
      #- {PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}:/etc/hyperledger/production
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    ports:
      - 10051:10051
      - 10053:10053
    networks:
      {SWARM_NET}:
        aliases:
          - {PEER_NAME1}.{ORG_2}.{DOMAIN_NAME}