--- #---------------- Peer0 org2 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {PEER_NAME0}-{ORG_2}
  name: {PEER_NAME0}-{ORG_2}
  namespace: {K8S_NS}
spec:
  type: ClusterIP
  ports:
    - name: "peer-core"
      port: 7051
      targetPort: 7051
  selector:
    app: {PEER_NAME0}-{ORG_2}
---
#---------------- Peer0 org2 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {PEER_NAME0}-{ORG_2}
    metrics-service: "true"
  name: {PEER_NAME0}-{ORG_2}-metrics
  namespace: {K8S_NS}
spec:
  type: ClusterIP
  ports:
    - name: "peer-metrics"
      port: 9443
      targetPort: 9443
  selector:
    app: {PEER_NAME0}-{ORG_2}
