--- #---------------- Peer0 org2 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-myorg2
  name: peer0-myorg2
  namespace: hlf
spec:
  type: ClusterIP
  ports:
    - name: "peer-core"
      port: 7051
      targetPort: 7051
  selector:
    app: peer0-myorg2
---
#---------------- Peer0 org2 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: peer0-myorg2
    metrics-service: "true"
  name: peer0-myorg2-metrics
  namespace: hlf
spec:
  type: ClusterIP
  ports:
    - name: "peer-metrics"
      port: 9443
      targetPort: 9443
  selector:
    app: peer0-myorg2
