--- #---------------- CLI Deployment ---------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cli-myorg2
  name: cli-myorg2
  namespace: hlf
spec:
  selector:
    matchLabels:
      app: cli-myorg2
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cli-myorg2
    spec:
      containers:
        - env:
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: CORE_PEER_ADDRESS
              value: peer0-myorg2:7051
            - name: CORE_PEER_ID
              value: cli-myorg2
            - name: CORE_PEER_LOCALMSPID
              value: Myorg2MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg2/users/Admin@myorg2/msp
            - name: CORE_PEER_TLS_CERT_FILE
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg2/peers/peer0-myorg2/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg2/peers/peer0-myorg2/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/myorg2/peers/peer0-myorg2/tls/ca.crt
            - name: GOPATH
              value: /opt/gopath
            - name: ORDERER_CA
              value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/sampledomaink8s.com/orderers/orderer0/msp/tlscacerts/tlsca.sampledomaink8s.com-cert.pem
          image: hyperledger/fabric-tools:2.2.0
          name: cli
          tty: true
          volumeMounts:
            # - mountPath: /host/var/run/
            #   name: cli-drv0
            - mountPath: /opt/gopath/src/github.com/marbles/
              name: cli-drv1
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/channel-artifacts
              name: cli-drv2
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
              name: cli-drv3
            - mountPath: /opt/gopath/src/github.com/fabcar/
              name: cli-fabcar
            - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/k8scripts
              name: cli-custom
          workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      restartPolicy: Always
      volumes:
        # - name: cli-drv0
        #   hostPath:
        #     path: /var/run/
        #     type: Directory
        - name: cli-drv1
          hostPath:
            path: {HOME_DIR_PATH}/k8s/chaincode
            type: Directory
        - name: cli-drv2
          hostPath:
            path: {HOME_DIR_PATH}/channel-artifacts
            type: Directory
        - name: cli-drv3
          hostPath:
            path: {HOME_DIR_PATH}/crypto-config
            type: Directory
        - name: cli-fabcar
          hostPath:
            path: {HOME_DIR_PATH}/k8s/fabcar
        - name: cli-custom
          hostPath:
            path: {HOME_DIR_PATH}/k8s/k8scripts
