version: '2'

services:    
    consul:
        container_name: consul
        image: consul:latest
        ports:
            - "8500:8500"
            - "8300:8300"
        entrypoint: /bin/consul   # < -- override the entry point here
        volumes:
            - ./config:/config
            - ./dhv/consul:/data
        command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1

    vault:
        container_name: vault
        image: vault
        links:
            - consul:consul
        depends_on:
            - consul
        ports:
            - "8200:8200"
        volumes_from:
            - consul
        cap_add:
            - IPC_LOCK
        environment:
          VAULT_ADDR: http://127.0.0.1:8200
          VAULT_LOCAL_CONFIG: |
            backend "consul" {
                  address = "consul:8500"
                  advertise_addr = "http://consul:8300"
                  scheme = "http"
            }
            listener "tcp" {
                address = "0.0.0.0:8200"
                #tls_cert_file = "/config/server.crt"
                #tls_key_file = "/config/server.key"
                tls_disable = 1
            }
            disable_mlock = true
        #command: server -config=/config/vault.hcl  # at some situation vault.hcl permission denied
        command: server 

    webui:
        container_name: webui
        image: djenriquez/vault-ui
        ports:
            - "8000:8000"
        links:
            - vault:vault
        environment:
            NODE_TLS_REJECT_UNAUTHORIZED: 0
            VAULT_URL_DEFAULT: http://vault:8200
            VAULT_AUTH_DEFAULT: USERNAMEPASSWORD
        command: start_app --verbose 

    backup:
        container_name: backup
        #build: backup/
        image: mcchae/vault-backup
        links:
            - consul:consul
        volumes:
            - ./dhv/backup:/backup/
        command: consul-backup
