#---------------- Peer0 Org1 Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {PEER_NAME0}-{ORG_1}
  name: {PEER_NAME0}-{ORG_1}
  namespace: {K8S_NS}
spec:
  type: ClusterIP
  ports:
  - name: "peer-core"
    port: 7051
    targetPort: 7051
  selector:
    app: {PEER_NAME0}-{ORG_1}
---
#---------------- Peer0 Org1 Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {PEER_NAME0}-{ORG_1}
    metrics-service: "true"
  name: {PEER_NAME0}-{ORG_1}-metrics
  namespace: {K8S_NS}
spec:
  type: ClusterIP
  ports:
  - name: "peer-metrics"
    port: 9443
    targetPort: 9443
  selector:
    app: {PEER_NAME0}-{ORG_1}
